Improved method of giving CW ammo on spawn
CFC-Servers/cfc_cw2_enhancements pull request #9
Opened 2020-07-28 22:58 UTC by Deconkle

Use the CustomizableWeaponry.ammoTypes table to give each ammo type to players when they spawn. Builders are also given 1000 cw ammo but it has no actual effect
tested, works on server

2020-07-28 23:13 UTC, plally commented on lua/autorun/server/sv_increase_starting_ammo.lua
> +    for AmmoName, bulletInfo in pairs(CustomizableWeaponry.ammoTypes) do
```suggestion
    for ammoName, bulletInfo in pairs(CustomizableWeaponry.ammoTypes) do
```
camelCase for all local variables

2020-07-28 23:14 UTC, plally commented on lua/autorun/server/sv_increase_starting_ammo.lua
> +            Ply:SetAmmo(1000,AmmoName)
```suggestion
            Ply:SetAmmo( 1000, AmmoName )
```
space inside parentheses and especially after commas

2020-07-28 23:17 UTC, plally commented on lua/autorun/server/sv_increase_starting_ammo.lua
> +hook.Add("PlayerSpawn", "CFC-Give-CW2-Ammo", givePlayerCWAmmo)
```suggestion
hook.Add( "PlayerSpawn", "CFC_CWEnhancements_GiveCW2Ammo", givePlayerCWAmmo )
```
spacing
hook names should be in the form `Organization_AddonName_Purpose`

2020-07-28 23:19 UTC, plally commented on lua/autorun/server/sv_increase_starting_ammo.lua
> +function givePlayerCWAmmo(Ply)
```suggestion
function givePlayerCWAmmo( Ply )
```
camelCase and spacing in parentheses

2020-07-28 23:22 UTC, plally commented on lua/autorun/server/sv_increase_starting_ammo.lua
> +BlacklistedAmmo = {
camelCase and make this variable local

2020-09-06 04:20 UTC, brandonsturgeon requested changes
Small refactor suggestion

2020-09-06 04:20 UTC, brandonsturgeon commented on lua/autorun/server/sv_increase_starting_ammo.lua
> +            ply:SetAmmo( 1000, ammoName )
Might be easier and more efficient to generate the list of "whitelisted" ammo types on init.

Underneath the `blacklistedAmmo`, a simple:
```lua
local cwAmmo = {}
```

then a new hook,
```lua
hook.Add( "Initialize", "CFC_CW2_GetAmmoTypes", function()
    for ammoName in pairs( CustomizableWeaponry.ammoTypes ) do
        cwAmmo[ammoName] = not blacklistedAmmo[ammoName]
    end
end )
```

Then this section can be:

```suggestion
function givePlayerCWAmmo( ply )
    for ammoName in pairs( cwAmmo ) do
        ply:SetAmmo( 1000, ammoName )
    end
end
```

2020-09-29 16:38 UTC, merged